### ISSUE TITLE
Dummy Player

### ISSUE THREAD

**Issue by kawashirosan** [kawashirosan/johnny#52]
## Summary
Implement a dummy player (NPC).

## Note
- Do not parametrize like `config.containsDummy`, but the dummy player should be added in a factory like `GameFactory.create` and we should be able to check if there is dummy with a method like `lazy val isThereDummy = …` by traversing ids of players (maybe `object DummyPlayerId extends PlayerId("dummy")`)

## Task
- [x] Join dummy at game creation
- [x] Dummy should not become a Werewolf.
- [ ] Werewolves should attack dummy if exists.

**Comment by kawashirosan** [comment]
- in first day wolves can attack only dummy
- dummy player must not be a wolf
